package com.example.victor.myapplication.query.musixmatch;

public enum MusixmatchQueryParameter {
    apikey,
    track_id,
    artist_id,
    album_id,
    commontrack_id,
    track_mbid,
    artist_mbid,
    album_mbid,
    q_track,
    q_artist,
    q_lyrics,
    q,
    f_has_lyrics,
    f_is_instrumental,
    f_has_subtitle,
    f_music_genre_id,
    f_subtitle_length,
    f_subtitle_length_max_deviation,
    f_lyrics_language,
    f_artist_id,
    f_artist_mbid,
    g_commontrack,
    s_track_rating,
    s_track_release_date,
    s_artist_rating,
    page,
    page_size,
    subtitle_format,
    country
}